### ISSUE TITLE
cxitoolでcxiに変換するよりもrsf使って一気に変換したほうがいい。

### ISSUE THREAD

**Issue by knight-ryu12** [togetg/TJAPlayer_for_3DS#2]
(Read Title)
elf+romfsで3dsxよりもciaに一気に変換できる。

**Comment by togetg** [comment]
正直makeromの使い方があまり分かっていないのでしばらくは現状のままにしようと思ってます

**Comment by knight-ryu12** [comment]
https://github.com/Steveice10/buildtools/blob/4524b3a324ae8e9dcaf80c4fe3694bc63628de22/3ds/template.rsf
これが参考になるかも。
